import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import NavBar from "@/components/layout/NavigationBar";
import FooterSection from "@/components/layout/FooterSection";

const myCustomFont = localFont({
  src: [
    {
      path: "../public/fonts/Helvetica-Light.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "../public/fonts/Helvetica.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/Helvetica-Bold.woff2",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--helvetica", // Opsional, untuk Tailwind
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${myCustomFont.variable} ${myCustomFont.className} antialiased`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
